# Site settings
profilepic: 'https://github.com/Jo941018/Jo941018.github.io/blob/a70a83428a820567110da548d0fff190da1c47c8/images/my_profile_picture.jpg'
title: Joel Sanchez
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joel Sanchez
user_description: I'm a Software Developer from México, always searching for the next challenge; no task is too scary nor too difficult.
user_title: Software Developer
email: computmx@gmail.com
# twitter_username: lorem_ipsum
instagram_username: joebox18
facebook_username: joe.sanchez.180
linkedin_username: 
github_username:  Jo941018
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']


